// Code generated by "stringer -type prop"; DO NOT EDIT

package utr50

import "fmt"

const _prop_name = "NURTuTr"

var _prop_index = [...]uint8{0, 1, 2, 3, 5, 7}

func (i prop) String() string {
	if i < 0 || i >= prop(len(_prop_index)-1) {
		return fmt.Sprintf("prop(%d)", i)
	}
	return _prop_name[_prop_index[i]:_prop_index[i+1]]
}
